#ifndef INSTRUCTIONS_H
#define INSTRUCTIONS_H

#include <stdint.h>
#include "cpu.h"

// Instruction opcodes
typedef enum {
    ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI,
    BNE, BPL, BRK, BVC, BVS, CLC, CLD, CLI,
    CLV, CMP, CPX, CPY, DEC, DEX, DEY, EOR,
    INC, INX, INY, JMP, JSR, LDA, LDX, LDY,
    LSR, NOP, ORA, PHA, PHP, PLA, PLP, ROL,
    ROR, RTI, RTS, SBC, SEC, SED, SEI, STA,
    STX, STY, TAX, TAY, TSX, TXA, TXS, TYA,
} instr;


typedef struct {
    const char *instr_name;     // instruction name
    const char *addrm_type;     // Address mode name
    bool pg_cross_cycle;    // Extra cycle on page cross?
    uint8_t opcode;     // opcode byte
    uint8_t cycles;     // Base cycles
    instr instruction;  // Instruction type
    addr_mode addrm;    // Addressing mode enum
}opcode;

// Macro for opcode definition list to condense raw definition
// macro: OP(0x11, ORA, INDIRECT, 5, *)
// raw: /* 0x11 */ {"ORA", "INDIRECT_Y", true, 5, instr::ORA, addr_mode::INDIRECT_Y,}

// general definition for any function name
#define _VFUNC_(name, n) name##n
#define _VFUNC(name, n) _VFUNC_(name, n)
#define VFUNC(func, ...) _VFUNC(func, __NARG__(__VA_ARGS__)) (__VA_ARGS__)
#define OP(...) VFUNC(OP, __VA_ARGS__)

// Invalid opcode
#define OP1(opcode) \
    {opcode, instr:: ins, addr_mode:: addrm, false, 0, "KIL", "----"}

// Standard opcode
#define OP4(opcode) \
    {opcode, instr:: ins, addr_mode:: addrm, false, cycles, #ins, #addrm}

// Opcode with extra cycle across pages
#define OP5(opcode) \
    {opcode, instr:: ins, addr_mode:: addrm, true, cycles, #ins, #addrm}

// Add opcode lookup table
const opcode opcodes[256] = {
    OP(0x00, BRK, IMPLIED_BRK, false, 0),
    OP(0x01, ORA, INDIRECT_X, false, 6),
    OP(0x02),
    OP(0x03),
    OP(0x04),
    OP(0x05, ORA, ZERO_PAGE, false, 3),
    OP(0x06, ASL, ZERO_PAGE, false, 5),
    OP(0x7),
    OP(0x08, PHP, IMPLIED, false, 3),
    OP(0x09, ORA, IMMEDIATE, false, 2),
    OP(0x0a, ASL, ACCUMULATOR, false, 2),
    OP(0x0b),
    OP(0x0c),
    OP(0x0d, ORA, ABSOLUTE, false, 4),
    OP(0x0e, ASL, ABSOLUTE, false, 4),
    OP(0x0f),
    OP(0x10, BPL, RELATIVE, true, 2),
    OP(0x11, ORA, INDIRECT_Y, true, 5),
    OP(0x12),
    OP(0x13),
    OP(0x14),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
    OP(0x , , , ),
}
#endif